import { describe, expect, it } from 'vitest'
import { calculateCartTotal, createOrder, updateOrderStatus, validateCheckout, validateQuantity } from '@/lib/business'

describe('validateQuantity', () => {
  it.each([[1, true], [10, true], [0, false], [11, false], [1.5, false], ['2', false]])('checks quantity %s', (value, valid) => expect(validateQuantity(value, 10).valid).toBe(valid))
  it('rejects quantities above stock', () => expect(validateQuantity(5, 3).valid).toBe(false))
})
describe('cart totals', () => it('sums line totals', () => expect(calculateCartTotal([{ productId: 1, price: 20000, quantity: 2, stock: 10 }, { productId: 2, price: 5000, quantity: 1, stock: 10 }])).toBe(45000)))
describe('checkout', () => { const base = { recipientName: 'A', shippingAddress: 'B', phone: 'C', lines: [{ productId: 1, price: 1, quantity: 1, stock: 1 }], isLoggedIn: true }; it('accepts valid input', () => expect(validateCheckout(base).valid).toBe(true)); it('rejects empty fields', () => expect(validateCheckout({ ...base, phone: '' }).valid).toBe(false)); it('rejects unauthenticated input', () => expect(validateCheckout({ ...base, isLoggedIn: false }).valid).toBe(false)) })
describe('order transitions', () => { it.each([['DRAFT', 'CONFIRMED'], ['DRAFT', 'CANCELLED'], ['CONFIRMED', 'COMPLETED'], ['CONFIRMED', 'CANCELLED']])('allows %s to %s', (a, b) => expect(updateOrderStatus(a as any, b as any)).toBe(b)); it.each([['DRAFT', 'COMPLETED'], ['COMPLETED', 'CANCELLED'], ['CANCELLED', 'DRAFT']])('rejects %s to %s', (a, b) => expect(() => updateOrderStatus(a as any, b as any)).toThrow()) })
describe('createOrder', () => { const products = [{ id: 1, price: 20000, stock: 3 }]; it('recomputes the authoritative total', () => { const result = createOrder({ isLoggedIn: true, recipientName: 'Raka', shippingAddress: 'Jl. Merdeka', phone: '0812', lines: [{ productId: 1, quantity: 2 }] }, products); expect(result.valid).toBe(true); if (result.valid) expect(result.total).toBe(40000) }); it('rejects unknown products', () => expect(createOrder({ isLoggedIn: true, recipientName: 'Raka', shippingAddress: 'Jl. Merdeka', phone: '0812', lines: [{ productId: 99, quantity: 1 }] }, products).valid).toBe(false)); it('rejects over-stock quantities', () => expect(createOrder({ isLoggedIn: true, recipientName: 'Raka', shippingAddress: 'Jl. Merdeka', phone: '0812', lines: [{ productId: 1, quantity: 4 }] }, products).valid).toBe(false)) })
